# This is a basic workflow to help you get started with Actions

name: Helm

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    container:
      image: alpine/k8s:1.25.6
      # env:
      #   NODE_ENV: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube/
          echo BREAK
          echo $KUBECONFIG > ~/.kube/config
          echo BREAK
          cd ~/.kube/
          echo BREAK
          ll
          echo BREAK
        # ls -l
        # kubectl version
        # kubectl get deployments
